AWSTemplateFormatVersion: "2010-09-09"

Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "MySNSTopic"
      DisplayName: "MySNSTopic"

  SnsEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref MySNSTopic
      Protocol: email
      Endpoint: Darshil.Patel@dal.ca
